
services:
  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    expose:
      - 8000
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  # продумать и реализовать подключение еще одного контейнера с базой данных
